kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: product-db-sql-storage-pvc
  labels:
    app.kubernetes.io/name: sql-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: product-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.db.storageClass }}
  accessModes:
    - {{ .Values.db.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.storage }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-db-sql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sql-db
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: product-db
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sql-db
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: product-db
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: product-db-sql-service
          image: "{{ .Values.image.repository }}/product-database-sql:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: product-db-sql-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.dbname }}
            - name: POSTGRES_USER
              value: {{ .Values.db.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-credentials
                  key: db-password
      volumes:
        - name: product-db-sql-storage
          persistentVolumeClaim:
            claimName: product-db-sql-storage-pvc
