FROM docker.io/postgres:17

# Define the database
ENV POSTGRES_DB=product_db

# Add the init.sql file to the /docker-entrypoint-initdb.d/ directory
ADD ./db/init.sql /docker-entrypoint-initdb.d/init.sql

# Change the permissions of the init.sql file to 755
RUN chmod -R 755 /docker-entrypoint-initdb.d/

# Change the owner of the /var/lib/postgresql directory to the postgres user
RUN sed -i /etc/passwd -e 's/postgres:x:70:70/postgres:x:10999:10999/g'
RUN sed -i /etc/group  -e 's/postgres:x:70/postgres:x:10999/g'
RUN chown -R 10999.10999 /var/lib/postgresql
