name: "Build Docker Images"

on:
  push:
  pull_request:

jobs:
  docker-db:
    name: "Build PostgreSQL Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          file: ./docker/Dockerfile.db
          tags: product-database-sql:1.0.0
