name: "Build Docker Images"

on:
  push:
  pull_request:

jobs:
  docker-db:
    name: "Build PostgreSQL Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          file: ./docker/Dockerfile.db
          tags: product-database-sql:1.0.0

  product-service-docker-image:
    name: "Build Product Service Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ./docker/Dockerfile.service
          tags: product-service:1.0.0
