name: "Build Docker Images"

on:
  push:
  pull_request:

jobs:
  docker-db:
    name: "Build PostgreSQL Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        # Only if the current branch is main
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # Push only if the branch is main
          push: ${{ github.ref == 'refs/heads/main' }}
          file: ./docker/Dockerfile.db
          tags: ghcr.io/sraesch/product-database-sql:0.1.1

  product-service-docker-image:
    name: "Build Product Service Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--release"
      - name: Login to GitHub Container Registry
        # Only if the current branch is main
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # Push only if the branch is main
          push: ${{ github.ref == 'refs/heads/main' }}
          context: .
          file: ./docker/Dockerfile.service
          tags: ghcr.io/sraesch/product-service:0.1.1
